import React, { useState, useEffect } from 'react';
import { Header } from './components/Header';
import { BottomNav, NavTab } from './components/BottomNav';
import { FlashcardViewer } from './components/FlashcardViewer';
import { DailyReviewSection } from './components/DailyReviewSection';
import { GenerateDeckSection } from './components/GenerateDeckSection';
import { DeckLibrarySection } from './components/DeckLibrarySection';
import { PracticeSentenceModal } from './components/PracticeSentenceModal';
import { WordDeepDiveModal } from './components/WordDeepDiveModal';
import { Deck, Flashcard, MasteryLevel, UserProgress } from './types';
import {
  loadSavedCards,
  saveCards,
  loadSavedDecks,
  saveDecks,
  loadUserProgress,
  saveUserProgress,
} from './utils/storage';
import { BookOpen, Sparkles } from 'lucide-react';

export default function App() {
  const [cards, setCards] = useState<Flashcard[]>(() => loadSavedCards());
  const [decks, setDecks] = useState<Deck[]>(() => loadSavedDecks());
  const [progress, setProgress] = useState<UserProgress>(() => loadUserProgress());
  const [activeDeckId, setActiveDeckId] = useState<string>(() => {
    const loadedDecks = loadSavedDecks();
    return loadedDecks[0]?.id || 'deck-daily-today';
  });
  const [activeTab, setActiveTab] = useState<NavTab>('learn');

  // Modals
  const [practiceCard, setPracticeCard] = useState<Flashcard | null>(null);
  const [deepDiveCard, setDeepDiveCard] = useState<Flashcard | null>(null);

  // Sync to localStorage
  useEffect(() => {
    saveCards(cards);
  }, [cards]);

  useEffect(() => {
    saveDecks(decks);
  }, [decks]);

  useEffect(() => {
    saveUserProgress(progress);
  }, [progress]);

  // Active deck cards
  const activeDeck = decks.find((d) => d.id === activeDeckId) || decks[0];
  const activeDeckCards = cards.filter((c) => c.deckId === activeDeck?.id);

  // Grading handler
  const handleGradeCard = (cardId: string, level: MasteryLevel) => {
    setCards((prevCards) =>
      prevCards.map((c) => {
        if (c.id === cardId) {
          return {
            ...c,
            masteryLevel: level,
            reviewCount: (c.reviewCount || 0) + 1,
            lastReviewed: new Date().toISOString(),
          };
        }
        return c;
      })
    );

    // Update progress
    setProgress((prev) => ({
      ...prev,
      totalCardsReviewed: prev.totalCardsReviewed + 1,
      todayCardsReviewed: prev.todayCardsReviewed + 1,
    }));
  };

  // When a new deck is generated by Gemini
  const handleDeckCreated = (newDeck: Deck, newCards: Flashcard[]) => {
    setDecks((prev) => [newDeck, ...prev]);
    setCards((prev) => [...newCards, ...prev]);
    setActiveDeckId(newDeck.id);
    setActiveTab('learn');
  };

  // Select a deck to study
  const handleSelectDeck = (deckId: string) => {
    setActiveDeckId(deckId);
    setActiveTab('learn');
  };

  // Delete a deck
  const handleDeleteDeck = (deckId: string) => {
    const remainingDecks = decks.filter((d) => d.id !== deckId);
    if (remainingDecks.length === 0) return;
    setDecks(remainingDecks);
    setCards((prev) => prev.filter((c) => c.deckId !== deckId));
    if (activeDeckId === deckId) {
      setActiveDeckId(remainingDecks[0].id);
    }
  };

  const needsReviewCount = cards.filter(
    (c) => c.masteryLevel === 'learning' || c.masteryLevel === 'review'
  ).length;

  return (
    <div className="min-h-screen bg-[#F5F2ED] text-[#4A453F] flex justify-center selection:bg-[#EAEFE8] selection:text-[#3D3934]">
      {/* Mobile container constraint: max-w-md matching the phone-native & desktop card frame */}
      <div className="w-full max-w-md min-h-screen bg-[#FAF9F6] border-x border-[#E0DBCF]/70 shadow-2xl flex flex-col relative pb-20">
        {/* Sticky App Header */}
        <Header progress={progress} activeDeckTitle={activeDeck?.title} />

        {/* Tab 1: Learn Active Deck */}
        {activeTab === 'learn' && (
          <main className="flex-1 flex flex-col pt-1">
            {/* Active Deck Selector / Header Info */}
            <div className="px-4 py-2.5 flex items-center justify-between border-b border-[#E0DBCF]/40 bg-[#FAF9F6]">
              <div className="flex items-center space-x-2 min-w-0">
                <BookOpen className="w-4 h-4 text-[#8FA189] shrink-0" />
                <span className="text-xs font-serif font-bold text-[#3D3934] truncate">
                  {activeDeck?.title || 'Bộ thẻ hôm nay'}
                </span>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-[#EBE7DF] text-[#6B655B] border border-[#DED9CE] font-semibold shrink-0">
                  {activeDeck?.level || 'B1-B2'}
                </span>
              </div>

              <button
                onClick={() => setActiveTab('generate')}
                className="text-[11px] font-semibold text-[#8FA189] hover:text-[#7D8F77] flex items-center space-x-1 shrink-0 ml-2 py-1 px-2 rounded-lg hover:bg-[#EAEFE8] transition-colors"
              >
                <Sparkles className="w-3.5 h-3.5 text-[#8FA189]" />
                <span>Thêm thẻ</span>
              </button>
            </div>

            <FlashcardViewer
              cards={activeDeckCards.length > 0 ? activeDeckCards : cards}
              onGradeCard={handleGradeCard}
              onOpenPractice={(card) => setPracticeCard(card)}
              onOpenDeepDive={(card) => setDeepDiveCard(card)}
            />
          </main>
        )}

        {/* Tab 2: Daily Review */}
        {activeTab === 'review' && (
          <main className="flex-1 flex flex-col pt-2">
            <DailyReviewSection
              cards={cards}
              onGradeCard={handleGradeCard}
              onSwitchToLearn={() => setActiveTab('learn')}
            />
          </main>
        )}

        {/* Tab 3: Generate Daily Deck with Gemini AI */}
        {activeTab === 'generate' && (
          <main className="flex-1 flex flex-col pt-2">
            <GenerateDeckSection
              existingWords={cards.map((c) => c.word)}
              onDeckCreated={handleDeckCreated}
            />
          </main>
        )}

        {/* Tab 4: Library & Stats */}
        {activeTab === 'library' && (
          <main className="flex-1 flex flex-col pt-2">
            <DeckLibrarySection
              decks={decks}
              cards={cards}
              activeDeckId={activeDeckId}
              progress={progress}
              onSelectDeck={handleSelectDeck}
              onDeleteDeck={handleDeleteDeck}
            />
          </main>
        )}

        {/* Fixed Mobile Bottom Navigation Bar */}
        <BottomNav
          activeTab={activeTab}
          onTabChange={setActiveTab}
          reviewCount={needsReviewCount}
        />

        {/* Modals */}
        <PracticeSentenceModal
          card={practiceCard}
          onClose={() => setPracticeCard(null)}
        />

        <WordDeepDiveModal
          card={deepDiveCard}
          onClose={() => setDeepDiveCard(null)}
        />
      </div>
    </div>
  );
}
